import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { FlatCompat } from "@eslint/eslintrc";

/**
 * ESLint 9 only reads flat config, and `eslint-config-next` 15.5 still ships
 * the old eslintrc shape: `index.js`, `core-web-vitals.js` and `typescript.js`,
 * no `exports` field and no flat entry point. `FlatCompat` is Next's own
 * documented bridge between the two, not a workaround, and it is what this
 * file exists to apply. When `eslint-config-next` gains a flat export, this
 * collapses to importing it directly.
 *
 * `next/core-web-vitals` is the stricter of the two Next presets: it promotes
 * the performance rules from warnings to errors. That is the right default for
 * a landing page, where the whole point is how fast it loads.
 */
const compat = new FlatCompat({
  baseDirectory: dirname(fileURLToPath(import.meta.url)),
});

/**
 * Named rather than exported inline because `next/core-web-vitals` turns on
 * `import/no-anonymous-default-export`, and this file is not exempt from the
 * rules it sets. A config that cannot pass itself is not worth trusting.
 */
const config = [
  {
    /**
     * Flat config ignores `node_modules` on its own and nothing else, so build
     * output has to be named. `.next-build` is this repo's own: `next build`
     * and `next dev` sharing one directory leaves the dev server serving chunks
     * that no longer exist, so the build was given its own.
     *
     * `next-env.d.ts` is generated by Next on every run and is gitignored.
     * Linting a file nobody can edit only produces findings nobody can fix.
     */
    ignores: [".next/**", ".next-build/**", "out/**", "next-env.d.ts"],
  },
  ...compat.extends("next/core-web-vitals", "next/typescript"),
];

export default config;
